#!/usr/bin/perl

use strict;
use warnings;

use Cwd qw(getcwd realpath);
use File::Temp qw();
use Test::More;

my $srcdir = getcwd;

ok(-x '/bin/sh', '/bin/sh must be executable');
ok(-x '/bin/dash', '/bin/dash must be executable');
ok(-x '/bin/bash', '/bin/bash must be executable');
ok(! -f '/bin/sh.distrib', '/bin/sh.distrib must not be present');
diag(qx(ls -l /bin/sh));
diag(qx(ls -l /bin/dash));
diag(qx(ls -l /bin/bash));

like(qx(dpkg -L dash),
     qr{^/usr/bin/sh$}m,
     'dash must contain a /usr/bin/sh symlink, for debootstrap');

is(qx(echo hello), "hello\n");

my $diverter = qx(dpkg-divert --listpackage /bin/sh);

ok($diverter eq "" or $diverter eq "LOCAL\n", '/bin/sh not diverted or local diversion');
ok($diverter ne "dash\n", '/bin/sh not diverted by dash');
ok($diverter ne "bash\n", '/bin/sh not diverted by bash');
ok(like(realpath('/bin/sh'), qr{^(?:/usr)?/bin/dash}));

my $diverter = qx(dpkg-divert --listpackage /usr/bin/sh);

ok($diverter eq "" or $diverter eq "LOCAL\n", '/usr/bin/sh not diverted or local diversion');
ok($diverter ne "dash\n", '/usr/bin/sh not diverted by dash');
ok($diverter ne "bash\n", '/usr/bin/sh not diverted by bash');
ok(like(realpath('/usr/bin/sh'), qr{^(?:/usr)?/bin/dash}));

my $tmpdir = File::Temp->newdir();
chdir $tmpdir;
is(system("apt-get download dash"), 0);
is(system("dpkg-deb -X *.deb ."), 0);
diag(qx(find . -ls));
chdir $srcdir;
like(readlink("$tmpdir/usr/bin/sh"), qr{^(?:/bin/)?[bd]ash$},
     'dash_*.deb must contain a /usr/bin/sh symlink for debootstrap');

done_testing;
